import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from 'next/font/google';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "TxniOS Portfolio",
  description: "Generated by txnio",
  icons: {
    icon: '/icons/cdrom.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`
          body, html {
            margin: 0;
            padding: 0;
            height: 100%;
            width: 100%;
            overflow: hidden;
            background-color: black;
          }
          #__next {
            height: 100%;
            width: 100%;
          }
          #content-wrapper {
            opacity: 0;
            transition: opacity 0.3s ease-in;
          }
        `}</style>
        <script dangerouslySetInnerHTML={{
          __html: `
            window.onload = function() {
              document.getElementById('content-wrapper').style.opacity = '1';
            }
          `
        }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${inter.className}`}
      >
        <div id="content-wrapper">
          {children}
        </div>
      </body>
    </html>
  );
}
