import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from 'next/font/google';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Antonio Gonzalez",
  description: "Generated by txnio",
  icons: {
    icon: [
      { url: '/o_30px_white.png', type: 'image/png' },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" href="/fonts/ChicagoKare-Regular.woff" as="font" type="font/woff" crossOrigin="anonymous" />
        <link rel="preload" href="/fonts/Renogare-Regular.otf" as="font" type="font/otf" crossOrigin="anonymous" />
        <link rel="preload" href="/fonts/geneva-12.otf" as="font" type="font/otf" crossOrigin="anonymous" />
        <link rel="preload" href="/fonts/ark-pixel-zh_tw.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
        <style>{`
          body, html {
            margin: 0;
            padding: 0;
            height: 100%;
            width: 100%;
            overflow: hidden;
            background-color: black;
          }
          #__next {
            height: 100%;
            width: 100%;
            overflow: hidden;
          }
          #content-wrapper {
            opacity: 1;
            transition: opacity 0.3s ease-in;
            height: 100%;
            width: 100%;
            overflow: hidden;
          }
        `}</style>
        <script dangerouslySetInnerHTML={{
          __html: `
            window.onload = function() {
              document.getElementById('content-wrapper').style.opacity = '1';
            }
          `
        }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${inter.className}`}
      >
        <div id="content-wrapper">
          {children}
        </div>
      </body>
    </html>
  );
}
