import type { DjTrack } from './dj/types';

export type AudioTrack = {
  id: string;
  title: string;
  artist: string;
  album: string;
  src: string;
  cover: string;
};

export const audioTracks: readonly AudioTrack[] = [
  {
    id: 'birds-are-still',
    title: 'Birds Are Still',
    artist: 'Takashi Yoshimatsu',
    album: 'Memo Flora',
    src: '/music/birds-are-still.mp3',
    cover: '/yoshimatsu.png',
  },
  {
    id: 'feisty',
    title: 'FEISTY',
    artist: 'Fred again..',
    album: 'Unknown Album',
    src: '/music/feisty.mp3',
    cover: '/music/cover/feisty.jpg',
  },
  {
    id: 'bunker-schranz',
    title: 'bunker schranz',
    artist: 'Leonswork',
    album: 'bunker schranz',
    src: '/music/bunker-schranz.mp3',
    cover: '/music/cover/bunker-schranz.jpg',
  },
  {
    id: 'gurre-lieder-prelude',
    title: 'Gurre-Lieder, Pt. 1: Prelude. Mäßig bewegt',
    artist: 'Arnold Schoenberg',
    album: 'Unknown Album',
    src: '/music/gurre-lieder-prelude.mp3',
    cover: '/music/cover/gurre-lieder-prelude.jpg',
  },
  {
    id: 'rukiawaa-track',
    title: 'ੴঐਁ目ਁ੍覚ਁめৡ੍৾৾એીૐೡૹೖೀ૰௸',
    artist: 'rukiawaa',
    album: '௰.̴͐ .᭒̶̄.̵͆悪ୗᔇੴᬼᔇ魔の覚ᬼ.̴͐ .̶̄.̵͆醒ໟଷࡡ',
    src: '/music/rukiawaa-track.mp3',
    cover: '/music/cover/rukiawaa-track.jpg',
  },
  {
    id: 'red-dragonfly',
    title: 'Red Dragonfly',
    artist: 'Cho Yong Pil',
    album: 'Best 2',
    src: '/music/red-dragonfly.mp3',
    cover: '/music/cover/red-dragonfly.jpg',
  },
  {
    id: 'on-the-level',
    title: 'On the Level',
    artist: 'Mac DeMarco',
    album: 'This Old Dog',
    src: '/music/on-the-level.mp3',
    cover: '/music/cover/on-the-level.jpg',
  },
  {
    id: 'funk-machine',
    title: 'Funk Machine',
    artist: 'DJANGO',
    album: 'Funk Machine',
    src: '/music/funk-machine.mp3',
    cover: '/music/cover/funk-machine.jpg',
  },
  {
    id: 'antarctica-echoes-remastered',
    title: 'Antarctica Echoes - Remastered',
    artist: 'Vangelis',
    album: 'Antarctica (Remastered)',
    src: '/music/antarctica-echoes-remastered.mp3',
    cover: '/music/cover/antarctica-echoes-remastered.jpg',
  },
];

export const djTracks: readonly DjTrack[] = [
  {
    id: 'cirkle-rythm-of-wexah',
    title: 'Rythm of Wexah',
    artist: 'Cirkle',
    album: 'DJ set reference',
    src: '',
    cover: '/icons/cdrom.png',
    available: false,
    bpm: null,
    beatOffsetSec: 0,
    keyCamelot: null,
    setOrder: 1,
    setPhase: 'opener',
  },
  {
    id: 'funk-assault-thats-the-funk-assault',
    title: "That's the Funk Assault",
    artist: 'Funk Assault',
    album: 'DJ set reference',
    src: '',
    cover: '/icons/cdrom.png',
    available: false,
    bpm: null,
    beatOffsetSec: 0,
    keyCamelot: null,
    setOrder: 2,
    setPhase: 'build',
  },
  {
    id: 'ned-bennett-pegasus',
    title: 'Pegasus',
    artist: 'Ned Bennett',
    album: 'DJ set reference',
    src: '',
    cover: '/icons/cdrom.png',
    available: false,
    bpm: null,
    beatOffsetSec: 0,
    keyCamelot: null,
    setOrder: 3,
    setPhase: 'build',
  },
  {
    id: 'selective-response-no-love-only-pleasure',
    title: 'No Love Only Pleasure',
    artist: 'Selective Response',
    album: 'DJ set reference',
    src: '',
    cover: '/icons/cdrom.png',
    available: false,
    bpm: null,
    beatOffsetSec: 0,
    keyCamelot: null,
    setOrder: 4,
    setPhase: 'build',
  },
  {
    id: 'industribal-tribe-1-alpha-chief',
    title: 'Tribe 1 (Alpha Chief)',
    artist: 'Industribal',
    album: 'DJ set reference',
    src: '',
    cover: '/icons/cdrom.png',
    available: false,
    bpm: null,
    beatOffsetSec: 0,
    keyCamelot: null,
    setOrder: 5,
    setPhase: 'peak',
  },
  {
    id: 'chris-liberator-guy-mcaffer-raw-19-a',
    title: 'Raw 19 A',
    artist: 'Chris Liberator & Guy McAffer',
    album: 'DJ set reference',
    src: '',
    cover: '/icons/cdrom.png',
    available: false,
    bpm: null,
    beatOffsetSec: 0,
    keyCamelot: null,
    setOrder: 6,
    setPhase: 'peak',
  },
  {
    id: 'dj-misjah-groovehead-trippin-out',
    title: "Trippin' Out",
    artist: 'DJ Misjah & Groovehead',
    album: 'DJ set reference',
    src: '',
    cover: '/icons/cdrom.png',
    available: false,
    bpm: null,
    beatOffsetSec: 0,
    keyCamelot: null,
    setOrder: 7,
    setPhase: 'peak',
  },
  {
    id: 'diego-pillow-rocker',
    title: 'Pillow Rocker',
    artist: 'Diego',
    album: 'DJ set reference',
    src: '',
    cover: '/icons/cdrom.png',
    available: false,
    bpm: null,
    beatOffsetSec: 0,
    keyCamelot: null,
    setOrder: 8,
    setPhase: 'release',
  },
  {
    ...audioTracks[2],
    available: true,
    bpm: null,
    beatOffsetSec: 0,
    keyCamelot: null,
    setOrder: 9,
    setPhase: 'peak',
  },
  {
    ...audioTracks[7],
    available: true,
    bpm: null,
    beatOffsetSec: 0,
    keyCamelot: null,
    setOrder: 10,
    setPhase: 'release',
  },
];
